/******************************************************************************
 * Shared infrastructure for the dedicated high-level LAPACKE tests.
 *
 * Each test lives in its own source file high_level/<x><routine>.c and
 * defines one test function via the LAPACKE_TEST macro:
 *
 *     #include "lapacke_test.h"
 *
 *     LAPACKE_TEST(dgels)
 *     {
 *         ...calls to lapacke_test_check(...)...
 *     }
 *
 * There is one runner per precision; their test tables are generated by
 * CMake from the routine names in LAPACKE/testing/high_level/CMakeLists.txt.
 * The file name (without extension) must match the name used in the
 * LAPACKE_TEST macro, otherwise the link fails.
 *
 * A routine test does three things, in both layouts. It sweeps a NaN over
 * every argument the high-level interface NaN-checks: a NaN inside the
 * documented input region must be rejected with the argument's error code,
 * a NaN anywhere else (an unreferenced triangle, the fill-in rows of a
 * band, the padding beyond the leading dimension) must be ignored. It hands
 * all-NaN input to the routine with the checks disabled, which must then
 * reach the Fortran routine (info not negative). And it schedules an
 * allocation failure at each of the routine's allocations in turn (the
 * high-level workspaces, then in row-major the transposed copies the middle
 * level makes), checking the error code of each, and that one allocation
 * past the last the call succeeds, so the count is exact; an invalid
 * matrix_layout must be rejected before any allocation. Each test wraps
 * refill, schedule and call in a LAPACKE_<X><ROUTINE>_ALLOC_TEST macro of
 * its own.
 *
 * The implementation is split by topic: check reporting in lapacke_test.c,
 * allocation tracking and failure injection in lapacke_test_alloc.c, test
 * matrix generation in lapacke_test_matgen_<x>.c, and the NaN position
 * sweeps in lapacke_test_nan_sweep.c.
 ******************************************************************************/

#ifndef LAPACKE_TEST_H
#define LAPACKE_TEST_H

#include <stddef.h>

#include "lapacke.h"

/** Defines the test function collected by the generated test runner. */
#define LAPACKE_TEST(name) void lapacke_test_fn_##name(void)

/* Dimensions of the shared test matrices. Rectangular (M > N) where the
 * routine allows it; LD leaves padding beyond the matrix in both layouts.
 * Buffers of LAPACKE_TEST_LD * LAPACKE_TEST_LD elements fit every layout. */
#define LAPACKE_TEST_M 4
#define LAPACKE_TEST_N 3
#define LAPACKE_TEST_NRHS 2
#define LAPACKE_TEST_LD 5

/** A matrix_layout value that is neither LAPACK_COL_MAJOR nor
 *  LAPACK_ROW_MAJOR, for the invalid-layout error tests. */
#define LAPACKE_TEST_INVALID_LAYOUT 0

/** Leading dimension under which the sweep macros treat a vector of len
 *  elements as a len-by-1 matrix in the given layout. */
#define LAPACKE_TEST_VLD(layout, len) ((layout) == LAPACK_COL_MAJOR ? (len) : 1)

/******************************************************************************/
/*                      Check reporting (lapacke_test.c)                      */
/******************************************************************************/

/** Global count of checks run, reported by the test runner. */
extern int lapacke_test_checks;
/** Global count of failed checks, reported by the test runner. */
extern int lapacke_test_failures;

/** Both matrix layouts (indices 0 and 1), for layout loops, plus
 *  LAPACKE_TEST_INVALID_LAYOUT (index 2) for the argument-error tests. */
extern const int lapacke_test_layouts[3];
/** Printable names matching lapacke_test_layouts. */
extern const char *lapacke_test_layout_names[3];

/* A quiet NaN of each element type, produced at run time (not folded by
 * the compiler); both parts for the complex types. */
double lapacke_create_nan(void);
float lapacke_test_snan(void);
double lapacke_test_dnan(void);
lapack_complex_float lapacke_test_cnan(void);
lapack_complex_double lapacke_test_znan(void);

/** Record one check of an info result against its expected value. */
void lapacke_test_check(const char *name, const char *variant, lapack_int info,
                        lapack_int expected);

/** Fill ipiv with the identity permutation 1, 2, ..., n (a valid pivot
 *  vector for any factored input). */
void lapacke_test_fill_ipiv(lapack_int n, lapack_int *ipiv);

/** Fill the first n entries of v with value. */
void lapacke_test_fill_int(lapack_int n, lapack_int *v, lapack_int value);

/******************************************************************************/
/*    Allocation failure injection and leak tracking (lapacke_test_alloc.c)   */
/******************************************************************************/

/** The counting/failing test allocator. */
void *lapacke_test_malloc(size_t size);

/** The deallocator matching lapacke_test_malloc. */
void lapacke_test_free(void *ptr);

/** Schedule the (countdown+1)-th LAPACKE allocation to fail once. */
void lapacke_test_schedule_malloc_failure(long countdown);

/** Record one check that a call consumed the scheduled countdown exactly. */
void lapacke_test_check_alloc_count(const char *name);

/** Record one check that every tracked allocation has been freed. */
void lapacke_test_check_leaks(const char *name);

/******************************************************************************/
/*             Test matrix generation (lapacke_test_matgen_<x>.c)             */
/******************************************************************************/

/* One set of fills per precision, <x> = s, d, c, z. The fill functions
 * write the whole buffer they are given, padding included. The random
 * matrices come from ?LATMS (well conditioned) with a fixed seed per fill,
 * so repeated calls produce identical data; where the real fills generate
 * symmetric matrices the complex ones generate Hermitian matrices, matching
 * what the complex routines read.
 *
 *   ?fill      a random general rows-by-cols matrix
 *   ?fill_spd  a random symmetric positive definite n-by-n matrix
 *   ?fill_sym  a random symmetric indefinite n-by-n matrix
 *   ?fill_tri  a random nonsingular uplo triangular n-by-n matrix
 *   ?fill_rhs  a random right-hand side (a general matrix, other seed)
 *   ?fill_nan  every position of a matrix buffer set to NaN
 *   ?fill_gb   a random m-by-n general band matrix (kl subdiagonals, ku
 *              superdiagonals) in the last kl+ku+1 of the rows rows of a
 *              band array: rows = 2*kl+ku+1 leaves the fill-in rows a band
 *              LU factorization writes above it; fill-in rows, band
 *              corners and padding get a finite sentinel
 *   ?fill_pb   a random symmetric positive definite band matrix with kd
 *              super/subdiagonals in the uplo band storage
 *   ?fill_tb   a random nonsingular triangular band matrix, likewise
 *   ?fill_pp   the uplo triangle of ?fill_spd's matrix, packed in the
 *              layout's order
 *   ?fill_sp   the same for ?fill_sym's matrix
 *   ?fill_tp   the same for ?fill_tri's matrix
 *   ?fill_vec  len deterministic nonzero values in (-0.5, 0.5) (nonzero
 *              real and imaginary parts for the complex precisions)
 *   ?fill_pos  len deterministic values in [2, 3) (real for the complex
 *              precisions)
 *
 * Band arrays are rows-by-n matrices in the given layout, so the sweep
 * macros treat them like any other matrix and the region helpers below
 * decide which positions hold matrix elements. Packed arrays and vectors
 * have no layout of their own: fill them once and sweep them as len-by-1
 * matrices with LAPACKE_TEST_VLD as leading dimension.
 */

/* single precision */
void lapacke_test_sfill(int layout, lapack_int rows, lapack_int cols, float *a,
                        lapack_int ld);
void lapacke_test_sfill_spd(int layout, lapack_int n, float *a, lapack_int ld);
void lapacke_test_sfill_sym(int layout, lapack_int n, float *a, lapack_int ld);
void lapacke_test_sfill_tri(int layout, char uplo, lapack_int n, float *a,
                            lapack_int ld);
void lapacke_test_sfill_rhs(int layout, lapack_int rows, lapack_int cols,
                            float *b, lapack_int ld);
void lapacke_test_sfill_nan(int layout, lapack_int rows, lapack_int cols,
                            float *a, lapack_int ld);
void lapacke_test_sfill_gb(int layout, lapack_int m, lapack_int n,
                           lapack_int kl, lapack_int ku, lapack_int rows,
                           float *ab, lapack_int ld);
void lapacke_test_sfill_pb(int layout, char uplo, lapack_int n, lapack_int kd,
                           float *ab, lapack_int ld);
void lapacke_test_sfill_tb(int layout, char uplo, lapack_int n, lapack_int kd,
                           float *ab, lapack_int ld);
void lapacke_test_sfill_pp(int layout, char uplo, lapack_int n, float *ap);
void lapacke_test_sfill_sp(int layout, char uplo, lapack_int n, float *ap);
void lapacke_test_sfill_tp(int layout, char uplo, lapack_int n, float *ap);
void lapacke_test_sfill_vec(lapack_int len, float *v);
void lapacke_test_sfill_pos(lapack_int len, float *v);

/* double precision */
void lapacke_test_dfill(int layout, lapack_int rows, lapack_int cols, double *a,
                        lapack_int ld);
void lapacke_test_dfill_spd(int layout, lapack_int n, double *a, lapack_int ld);
void lapacke_test_dfill_sym(int layout, lapack_int n, double *a, lapack_int ld);
void lapacke_test_dfill_tri(int layout, char uplo, lapack_int n, double *a,
                            lapack_int ld);
void lapacke_test_dfill_rhs(int layout, lapack_int rows, lapack_int cols,
                            double *b, lapack_int ld);
void lapacke_test_dfill_nan(int layout, lapack_int rows, lapack_int cols,
                            double *a, lapack_int ld);
void lapacke_test_dfill_gb(int layout, lapack_int m, lapack_int n,
                           lapack_int kl, lapack_int ku, lapack_int rows,
                           double *ab, lapack_int ld);
void lapacke_test_dfill_pb(int layout, char uplo, lapack_int n, lapack_int kd,
                           double *ab, lapack_int ld);
void lapacke_test_dfill_tb(int layout, char uplo, lapack_int n, lapack_int kd,
                           double *ab, lapack_int ld);
void lapacke_test_dfill_pp(int layout, char uplo, lapack_int n, double *ap);
void lapacke_test_dfill_sp(int layout, char uplo, lapack_int n, double *ap);
void lapacke_test_dfill_tp(int layout, char uplo, lapack_int n, double *ap);
void lapacke_test_dfill_vec(lapack_int len, double *v);
void lapacke_test_dfill_pos(lapack_int len, double *v);

/* single precision complex */
void lapacke_test_cfill(int layout, lapack_int rows, lapack_int cols,
                        lapack_complex_float *a, lapack_int ld);
void lapacke_test_cfill_spd(int layout, lapack_int n, lapack_complex_float *a,
                            lapack_int ld);
void lapacke_test_cfill_sym(int layout, lapack_int n, lapack_complex_float *a,
                            lapack_int ld);
void lapacke_test_cfill_tri(int layout, char uplo, lapack_int n,
                            lapack_complex_float *a, lapack_int ld);
void lapacke_test_cfill_rhs(int layout, lapack_int rows, lapack_int cols,
                            lapack_complex_float *b, lapack_int ld);
void lapacke_test_cfill_nan(int layout, lapack_int rows, lapack_int cols,
                            lapack_complex_float *a, lapack_int ld);
void lapacke_test_cfill_gb(int layout, lapack_int m, lapack_int n,
                           lapack_int kl, lapack_int ku, lapack_int rows,
                           lapack_complex_float *ab, lapack_int ld);
void lapacke_test_cfill_pb(int layout, char uplo, lapack_int n, lapack_int kd,
                           lapack_complex_float *ab, lapack_int ld);
void lapacke_test_cfill_tb(int layout, char uplo, lapack_int n, lapack_int kd,
                           lapack_complex_float *ab, lapack_int ld);
void lapacke_test_cfill_pp(int layout, char uplo, lapack_int n,
                           lapack_complex_float *ap);
void lapacke_test_cfill_sp(int layout, char uplo, lapack_int n,
                           lapack_complex_float *ap);
void lapacke_test_cfill_tp(int layout, char uplo, lapack_int n,
                           lapack_complex_float *ap);
void lapacke_test_cfill_vec(lapack_int len, lapack_complex_float *v);
void lapacke_test_cfill_pos(lapack_int len, lapack_complex_float *v);

/* double precision complex */
void lapacke_test_zfill(int layout, lapack_int rows, lapack_int cols,
                        lapack_complex_double *a, lapack_int ld);
void lapacke_test_zfill_spd(int layout, lapack_int n, lapack_complex_double *a,
                            lapack_int ld);
void lapacke_test_zfill_sym(int layout, lapack_int n, lapack_complex_double *a,
                            lapack_int ld);
void lapacke_test_zfill_tri(int layout, char uplo, lapack_int n,
                            lapack_complex_double *a, lapack_int ld);
void lapacke_test_zfill_rhs(int layout, lapack_int rows, lapack_int cols,
                            lapack_complex_double *b, lapack_int ld);
void lapacke_test_zfill_nan(int layout, lapack_int rows, lapack_int cols,
                            lapack_complex_double *a, lapack_int ld);
void lapacke_test_zfill_gb(int layout, lapack_int m, lapack_int n,
                           lapack_int kl, lapack_int ku, lapack_int rows,
                           lapack_complex_double *ab, lapack_int ld);
void lapacke_test_zfill_pb(int layout, char uplo, lapack_int n, lapack_int kd,
                           lapack_complex_double *ab, lapack_int ld);
void lapacke_test_zfill_tb(int layout, char uplo, lapack_int n, lapack_int kd,
                           lapack_complex_double *ab, lapack_int ld);
void lapacke_test_zfill_pp(int layout, char uplo, lapack_int n,
                           lapack_complex_double *ap);
void lapacke_test_zfill_sp(int layout, char uplo, lapack_int n,
                           lapack_complex_double *ap);
void lapacke_test_zfill_tp(int layout, char uplo, lapack_int n,
                           lapack_complex_double *ap);
void lapacke_test_zfill_vec(lapack_int len, lapack_complex_double *v);
void lapacke_test_zfill_pos(lapack_int len, lapack_complex_double *v);

/******************************************************************************/
/*               NaN position sweeps (lapacke_test_nan_sweep.c)               */
/******************************************************************************/

/* A sweep places a NaN in every position of the allocated buffer of a
 * matrix argument, one by one, and verifies that positions inside the
 * documented access region report the documented error code while all
 * other positions (unreferenced triangles, leading-dimension padding) are
 * ignored by the routine.
 *
 * A region maps logical coordinates (i, j) to nonzero if the routine reads
 * that element. The macros below cover the conventional-storage types;
 * routine-specific regions can be defined (as function-like macros or
 * functions) next to the test that needs them.
 */

/** Region of a full matrix: every element is read. */
#define lapacke_test_region_full(i, j) 1
/** Region of an upper triangular matrix: i <= j. */
#define lapacke_test_region_upper(i, j) ((i) <= (j))
/** Region of a lower triangular matrix: i >= j. */
#define lapacke_test_region_lower(i, j) ((i) >= (j))
/** Region of a unit-diagonal upper triangular matrix (the diagonal is not
 *  referenced): i < j. */
#define lapacke_test_region_strict_upper(i, j) ((i) < (j))
/** Region of a unit-diagonal lower triangular matrix (the diagonal is not
 *  referenced): i > j. */
#define lapacke_test_region_strict_lower(i, j) ((i) > (j))

/** Region of a band array holding a band with ku superdiagonals: element
 *  (i, j) of the array is matrix element (i + j - ku, j), referenced when
 *  that row exists in an m-row matrix. Band arrays with kl fill-in rows on
 *  top shift i by kl first. */
#define lapacke_test_region_band(i, j, m, ku)                                  \
    ((i) + (j) - (ku) >= 0 && (i) + (j) - (ku) < (m))

/** Nonzero if position p of an n-by-n triangle packed in the given layout
 *  and uplo holds a diagonal element (the positions a unit-diagonal packed
 *  triangular routine does not reference). */
int lapacke_test_packed_diag(int layout, char uplo, lapack_int n, lapack_int p);

/** Number of buffer positions a rows-by-cols matrix with leading dimension
 *  ld occupies in the given layout. */
size_t lapacke_test_alloc_len(int layout, lapack_int rows, lapack_int cols,
                              lapack_int ld);

/** Map a buffer position to logical matrix coordinates. */
int lapacke_test_map_position(int layout, lapack_int rows, lapack_int cols,
                              lapack_int ld, size_t p, lapack_int *i,
                              lapack_int *j);

/** Print the detail line for one misreported NaN sweep position. */
void lapacke_test_sweep_mismatch(const char *name, const char *variant,
                                 lapack_int i, lapack_int j, lapack_int info,
                                 lapack_int expected);
/** Record the one aggregated check of a finished NaN sweep. */
void lapacke_test_sweep_result(const char *name, const char *variant,
                               size_t positions, int mismatches);

/**
 * Run one NaN sweep over a matrix argument; counts as one check.
 *
 * Use the per-precision LAPACKE_TEST_[SDCZ]NAN_SWEEP wrappers below rather
 * than this macro: they supply the NaN of the matching element type.
 *
 * \param nan_fn       Function returning the NaN to plant, of mat's element
 *                     type.
 * \param name         Name of the sweep, printed on the report line.
 * \param layout_index Index into lapacke_test_layouts selecting the layout.
 * \param rows         Number of matrix rows.
 * \param cols         Number of matrix columns.
 * \param mat          Buffer of the matrix argument to sweep.
 * \param ld           Leading dimension of mat in the selected layout.
 * \param region       Region macro or function; NaNs inside it must yield
 *                     the info value expected, NaNs outside it must yield 0.
 * \param expected     Info value the routine must report for a NaN inside
 *                     the region.
 * \param reset_expr   Expression (use the comma operator to refill several
 *                     matrices) that restores all inputs of call_expr.
 * \param call_expr    Expression evaluating to the routine's info result.
 */
#define LAPACKE_TEST_NAN_SWEEP_IMPL(nan_fn, name, layout_index, rows, cols,    \
                                    mat, ld, region, expected, reset_expr,     \
                                    call_expr)                                 \
    do {                                                                       \
        const int lts_layout = lapacke_test_layouts[layout_index];             \
        const size_t lts_len = lapacke_test_alloc_len(lts_layout, rows, cols,  \
                                                      ld);                     \
        size_t lts_p;                                                          \
        int lts_bad = 0;                                                       \
        for (lts_p = 0; lts_p < lts_len; lts_p++) {                            \
            lapack_int lts_i, lts_j, lts_info, lts_want;                       \
            int lts_inside;                                                    \
            (void)(reset_expr);                                                \
            lts_inside = lapacke_test_map_position(lts_layout, rows, cols, ld, \
                                                   lts_p, &lts_i, &lts_j);     \
            (mat)[lts_p] = nan_fn();                                           \
            lts_info = (call_expr);                                            \
            lts_want = (lts_inside && region(lts_i, lts_j)) ? (expected) : 0;  \
            if (lts_info != lts_want) {                                        \
                lapacke_test_sweep_mismatch(                                   \
                    name, lapacke_test_layout_names[layout_index], lts_i,      \
                    lts_j, lts_info, lts_want);                                \
                lts_bad++;                                                     \
            }                                                                  \
        }                                                                      \
        lapacke_test_sweep_result(                                             \
            name, lapacke_test_layout_names[layout_index], lts_len, lts_bad);  \
    } while (0)

/* MSVC's legacy preprocessor substitutes __VA_ARGS__ as one single argument
 * when it is forwarded to a function-like macro. The extra rescan this
 * indirection forces splits it back into separate arguments; it is a no-op
 * for conforming preprocessors. */
#define LAPACKE_TEST_EXPAND(x) x

/** Run one NaN sweep over a single precision real matrix argument. */
#define LAPACKE_TEST_SNAN_SWEEP(...)                                           \
    LAPACKE_TEST_EXPAND(                                                       \
        LAPACKE_TEST_NAN_SWEEP_IMPL(lapacke_test_snan, __VA_ARGS__))
/** Run one NaN sweep over a double precision real matrix argument. */
#define LAPACKE_TEST_DNAN_SWEEP(...)                                           \
    LAPACKE_TEST_EXPAND(                                                       \
        LAPACKE_TEST_NAN_SWEEP_IMPL(lapacke_test_dnan, __VA_ARGS__))
/** Run one NaN sweep over a single precision complex matrix argument. */
#define LAPACKE_TEST_CNAN_SWEEP(...)                                           \
    LAPACKE_TEST_EXPAND(                                                       \
        LAPACKE_TEST_NAN_SWEEP_IMPL(lapacke_test_cnan, __VA_ARGS__))
/** Run one NaN sweep over a double precision complex matrix argument. */
#define LAPACKE_TEST_ZNAN_SWEEP(...)                                           \
    LAPACKE_TEST_EXPAND(                                                       \
        LAPACKE_TEST_NAN_SWEEP_IMPL(lapacke_test_znan, __VA_ARGS__))

#endif /* LAPACKE_TEST_H */
