name: Makefile

# This workflow builds and installs LAPACK using the Makefile build system.
# Only GFortran is tested.

on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/makefile.yml
    - '**Makefile'
    - 'BLAS/**'
    - 'CBLAS/**'
    - 'INSTALL/**'
    - 'LAPACKE/**'
    - 'SRC/**'
    - 'TESTING/**'
    - '!**README'
    - '!**CMakeLists.txt'
    - '!**md'
  pull_request:
    paths:
    - .github/workflows/makefile.yml
    - '**Makefile'
    - 'BLAS/**'
    - 'CBLAS/**'
    - 'INSTALL/**'
    - 'LAPACKE/**'
    - 'SRC/**'
    - 'TESTING/**'
    - '!**README'
    - '!**CMakeLists.txt'
    - '!**md'

permissions:
  contents: read

env:
  CFLAGS: "-O3 -flto -Wall -pedantic-errors"
  FFLAGS: "-O2 -flto -Wall -Wno-unused-dummy-argument -Wno-unused-variable -Wno-unused-label -Wmaybe-uninitialized -Werror=conversion -pedantic -fimplicit-none -frecursive -fopenmp -fcheck=all"
  LDFLAGS: ""
  AR: "ar"
  ARFLAGS: "cr"
  RANLIB: "ranlib"

defaults:
  run:
    shell: bash

jobs:
  build-install:
    name: ${{ matrix.toolchain.os }}-${{ matrix.toolchain.FC }}
    runs-on: ${{ matrix.toolchain.os }}

    env:
      FC: ${{ matrix.toolchain.FC }}
      CC: ${{ matrix.toolchain.CC }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
        - FC: gfortran
          CC: gcc
          os: ubuntu-26.04
        - FC: gfortran
          CC: gcc
          os: ubuntu-26.04-arm
        - FC: gfortran-14
          CC: gcc-14
          os: macos-26

    steps:
    - name: Checkout LAPACK
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set configurations
      run: |
        echo "SHELL = /bin/sh" >> make.inc
        echo "FFLAGS_DRV = ${{env.FFLAGS}}" >> make.inc
        echo "TIMER = INT_ETIME" >> make.inc
        echo "BLASLIB = ${{github.workspace}}/librefblas.a" >> make.inc
        echo "CBLASLIB = ${{github.workspace}}/libcblas.a" >> make.inc
        echo "LAPACKLIB = ${{github.workspace}}/liblapack.a" >> make.inc
        echo "TMGLIB = ${{github.workspace}}/libtmglib.a" >> make.inc
        echo "LAPACKELIB = ${{github.workspace}}/liblapacke.a" >> make.inc
        echo "DOCSDIR = ${{github.workspace}}/DOCS" >> make.inc

    - name: Build
      run: make -s -j"$(getconf _NPROCESSORS_ONLN)" all

    - name: Install
      run: make -j"$(getconf _NPROCESSORS_ONLN)" lapack_install
